# Lista 01 - Introdução e Revisão Numpy

[NumPy](http://numpy.org) é um pacote incrivelmente poderoso em Python, onipresente em qualquer projeto de ciência de dados. Possui forte integração com o [Pandas](http://pandas.pydata.org), outra ferramenta que iremos abordar na matéria. NumPy adiciona suporte para matrizes multidimensionais e funções matemáticas que permitem que você execute facilmente cálculos de álgebra linear. Este notebook será uma coleção de exemplos de álgebra linear computados usando NumPy.

## Numpy

Para fazer uso de Numpy precisamos importar a biblioteca

In [1]:
# -*- coding: utf8

import numpy as np

Quando pensamos no lado prático de ciência de dados, um aspecto chave que ajuda na implementação de novos algoritmos é a vetorização. De forma simples, vetorização consiste do uso de tipos como **escalar**, **vetor** e **matriz** para realizar uma computação mais eficaz (em tempo de execução).

Uma matriz é uma coleção de valores, normalmente representada por uma grade 𝑚 × 𝑛, onde 𝑚 é o número de linhas e 𝑛 é o número de colunas. Os comprimentos das arestas 𝑚 e 𝑛 não precisam ser necessariamente diferentes. Se tivermos 𝑚 = 𝑛, chamamos isso de matriz quadrada. Um caso particularmente interessante de uma matriz é quando 𝑚 = 1 ou 𝑛 = 1. Nesse caso, temos um caso especial de uma matriz que chamamos de vetor. Embora haja um objeto de matriz em NumPy, faremos tudo usando matrizes NumPy porque elas podem ter dimensões maiores que 2.

1. **Escalar:** Um vetor de zero dimensões

In [2]:
1

1

In [3]:
np.array(1)

array(1)

2. **Vetor:** Representa uma dimensão

Abaixo vamos criar um vetor simples. Inicialmente, vamos criar uma lista.

In [4]:
data_list = [3.5, 5, 2, 8, 4.2]

Observe o tipo da mesma.

In [5]:
type(data_list)

list

Embora vetores e listas sejam parecidos, vetores Numpy são otimizados para operações de Álgebra Linear. Ciência de Dados faz bastante uso de tais operações, sendo este um dos motivos da dependência em Numpy.

Abaixo criamos um vetor.

In [6]:
data = np.array(data_list)
print(data)
print(type(data))

[3.5 5.  2.  8.  4.2]
<class 'numpy.ndarray'>


Observe como podemos somar o mesmo com um número. Não é possível fazer tal operação com listas.

In [7]:
data + 7

array([10.5, 12. ,  9. , 15. , 11.2])

3. **Matrizes:** Representam duas dimensões.

In [8]:
X = np.array([[2, 4],
              [1, 3]])
X

array([[2, 4],
       [1, 3]])

Podemos indexar as matrizes e os vetores.

In [9]:
data[0]

np.float64(3.5)

In [10]:
X[0, 1] # aqui é primeira linha, segunda coluna

np.int64(4)

Podemos também criar vetores/matrizes de números aleatórios

In [11]:
X = np.random.randn(4, 3) # Gera números aleatórios de uma normal
print(X)

[[-0.74476389 -0.5685493  -0.1398443 ]
 [ 0.6506493  -0.64032697 -0.54118282]
 [-0.65724438  1.0655388   1.11374946]
 [ 0.66941604  0.34275264 -0.64720005]]


### Indexando

Pegando a primeira linha

In [12]:
X[0] # observe que 0 é a linha 1, compare com o X[0, 1] de antes.

array([-0.74476389, -0.5685493 , -0.1398443 ])

In [13]:
X[1] # segunda

array([ 0.6506493 , -0.64032697, -0.54118282])

In [14]:
X[2] # terceira

array([-0.65724438,  1.0655388 ,  1.11374946])

Observe como todos os tipos retornados são `array`. Array é o nome genérico de Numpy para vetores e matrizes.

`X[:, c]` pega uma coluna

In [15]:
X[:, 0]

array([-0.74476389,  0.6506493 , -0.65724438,  0.66941604])

In [16]:
X[:, 1]

array([-0.5685493 , -0.64032697,  1.0655388 ,  0.34275264])

`X[um_vetor]` pega as linhas da matriz. `X[:, um_vetor]` pega as colunas

In [17]:
X[[0, 0, 1]] # observe que pego a primeira linha, indexada por 0, duas vezes

array([[-0.74476389, -0.5685493 , -0.1398443 ],
       [-0.74476389, -0.5685493 , -0.1398443 ],
       [ 0.6506493 , -0.64032697, -0.54118282]])

Abaixo pego a segunda a primeira coluna

In [18]:
X[:, [1, 0]]

array([[-0.5685493 , -0.74476389],
       [-0.64032697,  0.6506493 ],
       [ 1.0655388 , -0.65724438],
       [ 0.34275264,  0.66941604]])

### Indexação Booleana

`X[vetor_booleano]` retorna as linhas (ou colunas quando X[:, vetor_booleano]) onde o vetor é true

In [19]:
X[[True, False, True, False]]

array([[-0.74476389, -0.5685493 , -0.1398443 ],
       [-0.65724438,  1.0655388 ,  1.11374946]])

In [20]:
X[:, [False, True, True]]

array([[-0.5685493 , -0.1398443 ],
       [-0.64032697, -0.54118282],
       [ 1.0655388 ,  1.11374946],
       [ 0.34275264, -0.64720005]])

### Reshape, Flatten e Ravel

Todo vetor ou matriz pode ser redimensionado. Observe como uma matriz abaixo de 9x8=72 elementos. Podemos redimensionar os mesmos para outros arrays de tamanho 72.

In [21]:
X = np.random.randn(9, 8)

Criando uma matriz de 18x4.

In [22]:
X.reshape((18, 4))

array([[-0.86732264, -0.05263662,  1.52810851,  1.20881162],
       [ 0.42343581, -0.1457651 , -0.10567191,  1.00638577],
       [ 0.35649745,  0.8088684 , -0.51252348, -0.13322638],
       [-0.21333043, -0.67221524,  0.68284344, -0.3921671 ],
       [-0.67869462,  0.07146738, -0.67655964,  0.64603039],
       [ 0.19361904,  0.28070921, -3.11291182, -0.84123856],
       [ 1.35607689, -0.17750495,  0.79896856, -0.38267411],
       [ 0.926941  ,  0.20742245,  0.08207559, -0.77098624],
       [-1.437063  ,  0.56771947,  2.06152777, -1.81096856],
       [ 0.23449442, -0.89230962, -0.04199461,  0.07499537],
       [-0.43598272,  1.8948591 , -1.38986718,  2.69899683],
       [ 0.54978827,  1.96562226, -0.38493396, -0.35719527],
       [-0.00558647, -0.49504195,  0.23230951,  0.30668535],
       [-0.86150227, -0.95760774,  0.31448807, -0.32266668],
       [ 0.9249128 , -0.92575887,  0.43402917, -0.66366891],
       [ 0.03495915, -1.40671155, -1.443684  , -0.90928135],
       [ 1.30867356,  2.

Ou um vetor de 72

In [23]:
X.reshape(72)

array([-0.86732264, -0.05263662,  1.52810851,  1.20881162,  0.42343581,
       -0.1457651 , -0.10567191,  1.00638577,  0.35649745,  0.8088684 ,
       -0.51252348, -0.13322638, -0.21333043, -0.67221524,  0.68284344,
       -0.3921671 , -0.67869462,  0.07146738, -0.67655964,  0.64603039,
        0.19361904,  0.28070921, -3.11291182, -0.84123856,  1.35607689,
       -0.17750495,  0.79896856, -0.38267411,  0.926941  ,  0.20742245,
        0.08207559, -0.77098624, -1.437063  ,  0.56771947,  2.06152777,
       -1.81096856,  0.23449442, -0.89230962, -0.04199461,  0.07499537,
       -0.43598272,  1.8948591 , -1.38986718,  2.69899683,  0.54978827,
        1.96562226, -0.38493396, -0.35719527, -0.00558647, -0.49504195,
        0.23230951,  0.30668535, -0.86150227, -0.95760774,  0.31448807,
       -0.32266668,  0.9249128 , -0.92575887,  0.43402917, -0.66366891,
        0.03495915, -1.40671155, -1.443684  , -0.90928135,  1.30867356,
        2.24342553,  0.22585024,  0.82173902,  1.71147724,  0.14

A chamada flatten e ravel faz a mesma coisa, criam uma visão de uma dimensão da matriz.

In [24]:
X.flatten()

array([-0.86732264, -0.05263662,  1.52810851,  1.20881162,  0.42343581,
       -0.1457651 , -0.10567191,  1.00638577,  0.35649745,  0.8088684 ,
       -0.51252348, -0.13322638, -0.21333043, -0.67221524,  0.68284344,
       -0.3921671 , -0.67869462,  0.07146738, -0.67655964,  0.64603039,
        0.19361904,  0.28070921, -3.11291182, -0.84123856,  1.35607689,
       -0.17750495,  0.79896856, -0.38267411,  0.926941  ,  0.20742245,
        0.08207559, -0.77098624, -1.437063  ,  0.56771947,  2.06152777,
       -1.81096856,  0.23449442, -0.89230962, -0.04199461,  0.07499537,
       -0.43598272,  1.8948591 , -1.38986718,  2.69899683,  0.54978827,
        1.96562226, -0.38493396, -0.35719527, -0.00558647, -0.49504195,
        0.23230951,  0.30668535, -0.86150227, -0.95760774,  0.31448807,
       -0.32266668,  0.9249128 , -0.92575887,  0.43402917, -0.66366891,
        0.03495915, -1.40671155, -1.443684  , -0.90928135,  1.30867356,
        2.24342553,  0.22585024,  0.82173902,  1.71147724,  0.14

In [25]:
X.ravel()

array([-0.86732264, -0.05263662,  1.52810851,  1.20881162,  0.42343581,
       -0.1457651 , -0.10567191,  1.00638577,  0.35649745,  0.8088684 ,
       -0.51252348, -0.13322638, -0.21333043, -0.67221524,  0.68284344,
       -0.3921671 , -0.67869462,  0.07146738, -0.67655964,  0.64603039,
        0.19361904,  0.28070921, -3.11291182, -0.84123856,  1.35607689,
       -0.17750495,  0.79896856, -0.38267411,  0.926941  ,  0.20742245,
        0.08207559, -0.77098624, -1.437063  ,  0.56771947,  2.06152777,
       -1.81096856,  0.23449442, -0.89230962, -0.04199461,  0.07499537,
       -0.43598272,  1.8948591 , -1.38986718,  2.69899683,  0.54978827,
        1.96562226, -0.38493396, -0.35719527, -0.00558647, -0.49504195,
        0.23230951,  0.30668535, -0.86150227, -0.95760774,  0.31448807,
       -0.32266668,  0.9249128 , -0.92575887,  0.43402917, -0.66366891,
        0.03495915, -1.40671155, -1.443684  , -0.90928135,  1.30867356,
        2.24342553,  0.22585024,  0.82173902,  1.71147724,  0.14

As funções incorporadas ao NumPy podem ser facilmente chamadas em matrizes. A maioria das funções são aplicadas a um elemento de array (como a multiplicação escalar). Por exemplo, se chamarmos `log()` em um array, o logaritmo será obtido de cada elemento.

In [26]:
np.log(data)

array([1.25276297, 1.60943791, 0.69314718, 2.07944154, 1.43508453])

Mean tira a média

In [27]:
np.mean(data)

np.float64(4.54)

Algumas funções podem ser chamadas direto no vetor, nem todas serão assim. O importante é ler a [documentação](http://numpy.org) e aprender. Com um pouco de prática você vai se acostumando.

In [28]:
data.mean()

np.float64(4.54)

Abaixo temos a mediana,

In [29]:
np.median(data) # por exemplo, não existe data.median(). Faz sentido? Não. Mas é assim.

np.float64(4.2)

Em matrizes as funções operam em todos os elemntos.

In [30]:
np.median(X)

np.float64(0.05307261976807524)

In [31]:
X.mean()

np.float64(0.05600364660339416)

In [32]:
np.log(X + 10)

array([[2.2118589 , 2.29730753, 2.44478827, 2.41670022, 2.34405671,
        2.2879013 , 2.29196167, 2.39847563],
       [2.3376141 , 2.38036695, 2.24997267, 2.28917291, 2.28102121,
        2.23299755, 2.36863904, 2.26257869],
       [2.23230268, 2.30970641, 2.2325317 , 2.36518709, 2.32176194,
        2.33026925, 1.92964838, 2.21471096],
       [2.42975301, 2.28467517, 2.37945063, 2.26356625, 2.39123139,
        2.32311515, 2.31075915, 2.22235219],
       [2.14744324, 2.35780402, 2.49002086, 2.10279563, 2.32576382,
        2.20911915, 2.29837679, 2.31005665],
       [2.25800786, 2.4761063 , 2.15293974, 2.541523  , 2.35610579,
        2.48203773, 2.26333125, 2.26621201],
       [2.30202629, 2.25181356, 2.32555031, 2.33279275, 2.21249601,
        2.20192377, 2.33354952, 2.26978638],
       [2.39104576, 2.20543975, 2.3450725 , 2.23391336, 2.30607491,
        2.15098149, 2.14666972, 2.20725396],
       [2.42557   , 2.5049891 , 2.32491885, 2.38155698, 2.46056932,
        2.31668632, 2.209537

Porém, caso você queira a media de linhas ou colunas use `axis`. Antes, vamos ver o tamanho do vetor.

In [33]:
X.shape

(9, 8)

In [34]:
np.mean(X, axis=0) # média das colunas. como temos 8 colunas, temos 8 elementos.

array([ 0.05794569,  0.43726639,  0.30020483,  0.29908058,  0.33332025,
       -0.16431602, -0.54425388, -0.27121866])

In [35]:
np.mean(X, axis=0).shape

(8,)

In [36]:
np.mean(X, axis=1) # média das linhas

array([ 0.37441818, -0.00940667, -0.51469733,  0.2550399 , -0.15544985,
        0.56766091, -0.22361527, -0.49440045,  0.70448339])

In [37]:
np.mean(X, axis=1).shape

(9,)

Lembre-se que eixo 0 é coluna. Eixo 1 é linas.

### Multiplicação de Matrizes

Para transpor uma matriz fazemos uso de .T

In [38]:
X.shape

(9, 8)

In [39]:
X.T.shape

(8, 9)

In [40]:
X.T

array([[-0.86732264,  0.35649745, -0.67869462,  1.35607689, -1.437063  ,
        -0.43598272, -0.00558647,  0.9249128 ,  1.30867356],
       [-0.05263662,  0.8088684 ,  0.07146738, -0.17750495,  0.56771947,
         1.8948591 , -0.49504195, -0.92575887,  2.24342553],
       [ 1.52810851, -0.51252348, -0.67655964,  0.79896856,  2.06152777,
        -1.38986718,  0.23230951,  0.43402917,  0.22585024],
       [ 1.20881162, -0.13322638,  0.64603039, -0.38267411, -1.81096856,
         2.69899683,  0.30668535, -0.66366891,  0.82173902],
       [ 0.42343581, -0.21333043,  0.19361904,  0.926941  ,  0.23449442,
         0.54978827, -0.86150227,  0.03495915,  1.71147724],
       [-0.1457651 , -0.67221524,  0.28070921,  0.20742245, -0.89230962,
         1.96562226, -0.95760774, -1.40671155,  0.14201114],
       [-0.10567191,  0.68284344, -3.11291182,  0.08207559, -0.04199461,
        -0.38493396,  0.31448807, -1.443684  , -0.88849573],
       [ 1.00638577, -0.3921671 , -0.84123856, -0.77098624,  0

Para multiplicar matrizes, do ponto de visto de multiplicação matricial como definido na álgebra linear, fazemos uso de `@`.

In [41]:
X @ X.T

array([[ 5.77588454e+00, -1.75518648e+00, -1.44637655e-01,
        -8.30800797e-01,  2.48690559e+00,  1.04459095e+00,
         1.73456739e-01, -1.43515457e+00,  9.54853010e-01],
       [-1.75518648e+00,  2.17924151e+00, -1.94918796e+00,
         2.57491832e-03, -3.76698691e-01,  1.68649695e-01,
         6.06450523e-01, -2.44184798e-01,  9.60751391e-01],
       [-1.44637655e-01, -1.94918796e+00,  1.18550105e+01,
        -1.09002879e+00, -1.68622728e+00,  5.27225141e+00,
        -1.13377755e+00,  3.45458358e+00,  2.72737203e+00],
       [-8.30800797e-01,  2.57491832e-03, -1.09002879e+00,
         4.15864265e+00,  2.61576009e-01, -1.90973491e+00,
        -5.74063597e-01,  2.34249793e+00,  2.73051924e+00],
       [ 2.48690559e+00, -3.76698691e-01, -1.68622728e+00,
         2.61576009e-01,  1.07755513e+01, -7.68640933e+00,
         2.65557963e-01,  1.49777243e+00, -1.31229238e+00],
       [ 1.04459095e+00,  1.68649695e-01,  5.27225141e+00,
        -1.90973491e+00, -7.68640933e+00,  1.743858

O uso de `*` realiza uma operação ponto a ponto

In [42]:
X * X

array([[7.52248554e-01, 2.77061342e-03, 2.33511562e+00, 1.46122553e+00,
        1.79297884e-01, 2.12474647e-02, 1.11665519e-02, 1.01281231e+00],
       [1.27090433e-01, 6.54268085e-01, 2.62680321e-01, 1.77492692e-02,
        4.55098719e-02, 4.51873332e-01, 4.66275165e-01, 1.53795036e-01],
       [4.60626390e-01, 5.10758587e-03, 4.57732948e-01, 4.17355263e-01,
        3.74883310e-02, 7.87976614e-02, 9.69022001e+00, 7.07682311e-01],
       [1.83894454e+00, 3.15080062e-02, 6.38350755e-01, 1.46439476e-01,
        8.59219609e-01, 4.30240741e-02, 6.73640245e-03, 5.94419789e-01],
       [2.06515008e+00, 3.22305397e-01, 4.24989674e+00, 3.27960711e+00,
        5.49876312e-02, 7.96216451e-01, 1.76354715e-03, 5.62430545e-03],
       [1.90080934e-01, 3.59049101e+00, 1.93173078e+00, 7.28458388e+00,
        3.02267141e-01, 3.86367085e+00, 1.48174155e-01, 1.27588463e-01],
       [3.12086903e-05, 2.45066530e-01, 5.39677103e-02, 9.40559028e-02,
        7.42186167e-01, 9.17012577e-01, 9.89027439e-02, 1.

Observe a diferença de tamanhos

In [43]:
(X * X).shape

(9, 8)

In [44]:
(X @ X.T).shape

(9, 9)

**Pense:** Para o nosso `X` de tamanho `(9, 8)`, qual o motivo de `X * X.T` não funcionar? Qual o motivo de `X @ X` não funcionar?

## Correção Automática

Nossa correção automática depende das funções abaixo. Tais funções comparam valores que serão computados pelo seu código com uma saída esperada. Normalmente, vocês não fazer uso de tais funções em notebooks como este. Porém, elas são chave em ambientes de testes automáticos (fora do nosso escopo).

Observe como algumas funções comparam valores e outras comparam vetores. Além do mais, temos funções para comparar dentro de algumas casas decimais.

In [45]:
from numpy.testing import assert_almost_equal
from numpy.testing import assert_equal

from numpy.testing import assert_array_almost_equal
from numpy.testing import assert_array_equal

In [46]:
# caso você mude um dos valores vamos receber um erro!
assert_array_equal(2, 2)

# caso você mude um dos valores vamos receber um erro!
assert_array_equal([1, 2], [1, 2])

# caso você mude um dos valores vamos receber um erro!
assert_almost_equal(3.1415, 3.14, 1)

Caso você mude um dos valores abaixo vamos receber um erro! Como o abaixo.

```
-----------------------------------------------------------------------
AssertionError                        Traceback (most recent call last)
<ipython-input-10-396672d880f2> in <module>
----> 1 assert_equal(2, 3) # caso você mude um dos valores vamos receber um erro!

~/miniconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py in assert_equal(actual, desired, err_msg, verbose)
    413         # Explicitly use __eq__ for comparison, gh-2552
    414         if not (desired == actual):
--> 415             raise AssertionError(msg)
    416
    417     except (DeprecationWarning, FutureWarning) as e:

AssertionError:
Items are not equal:
 ACTUAL: 2
 DESIRED: 3
 ```

É essencial que todo seu código execute sem erros! Portanto, antes de submeter clique em `Kernel` no menu acima. Depois clique em `Restart & Execute All.`

**Garanta que o notebook executa até o fim!** Isto é, sem erros como o acima.

## Funções em Python

Para criar uma função em Python fazemos uso da palavra-chave:
```python
def
```

Todos nossos exercícios farão uso de funções. **Mantenha a assinatura das funções exatamente como requisitado, a correção automática depende disso.** Abaixo, temos um exempo de uma função que imprime algo na tela!

In [47]:
def print_something(txt):
    print(f'Voce passou o argumento: {txt}')

In [48]:
print_something('DCC 212')

Voce passou o argumento: DCC 212


Podemos também dizer o tipo do argumento, porém faremos pouco uso disto em ICD.

In [49]:
def print_something(txt: str):
    print(f'Voce passou o argumento: {txt}')

In [50]:
print_something('DCC 212')

Voce passou o argumento: DCC 212


Abaixo temos uma função que soma, a soma, dois vetores

In [51]:
def sum_of_sum_vectors(array_1, array_2):
    return (array_1 + array_2).sum()

In [52]:
x = np.array([1, 2])
y = np.array([1, 2])

In [53]:
sum_of_sum_vectors(x, y)

np.int64(6)

Abaixo temos um teste, tais testes vão avaliar o seu código. Nem todos estão aqui no notebook!

In [54]:
assert_equal(6, sum_of_sum_vectors(x, y))

## Exercício 01

Inicialmente, crie uma função que recebe duas listas de números, converte as duas para um vetor numpy usando `np.array` e retorna o produto interno das duas listas.

__Dicas:__  
1. Tente fazer um código sem nenhum **for**! Ou seja, numpy permite operações em vetores e matrizes, onde: `np.array([1, 2]) + np.array([2, 2]) = np.array([3, 4])`.

__Funções:__
1. `np.sum(array)` soma os elementos do array. `array.sum()` tem o mesmo efeito!

In [55]:
def inner(array_1, array_2):
    #cria os arrays numpy
    np.array(array_1)
    np.array(array_2)

    if len(array_1) != len(array_2):
        print("ERRO: as listas não têm o mesmo tamanho para o produto interno")
        return 0
    return (array_1 * array_2).sum()

In [56]:
x1 = np.array([2, 4, 8])
x2 = np.array([10, 100, 1000])
assert_equal(20 + 400 + 8000, inner(x1, x2))

## Exercício 02

Implemente uma função utilizando numpy que recebe duas matrizes, multiplica as duas e retorne o valor médio das células da multiplicação. Por exemplo, ao multiplicar:

```
[1 2]
[3 4]

com

[2 1]
[1 2]

temos

[4  5 ]
[10 11]

onde a média de [4, 5, 10, 11] é

7.5, sua resposta final!
```


__Dicas:__  
1. Use o operador @ para multiplicar matrizes!

In [57]:
def medmult(X_1, X_2):
    return np.mean(X_1 @ X_2)


In [58]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([2, 1, 1, 2]).reshape(2, 2)
assert_equal(7.5, medmult(X, Y))